version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biblioteca
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway:9.16.1
    command: -url=jdbc:postgresql://db:5432/biblioteca -user=postgres -password=postgres -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./infra/flyway/sql:/flyway/sql
    depends_on:
      - db

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/biblioteca
    ports:
      - "8000:8000"
    depends_on:
      - db
      - flyway

volumes:
  pgdata:
